### ISSUE TITLE
How do I make the timer to add "0" to the seconds?

### ISSUE THREAD

**Issue by Reasonab1e** [abobykin/bingo#2]
![bandicam 2024-06-27 14-17-45-005](https://github.com/abobykin/bingo/assets/159224692/78fc5272-9b74-4c8d-b9d5-07958e163e7a)

**Comment by abobykin** [comment]
In this line ````${minutes}:${seconds}```` you need to check the string of seconds for length with a condition (exactly as a string, for this you can use the toString() or String() methods, the reference book helps), and if the length is more than less than two characters (the case as in your screenshot), you need to add another zero ("0") to the string (there after the colon), and if the condition is false (in the else part of the type) do not add "0".

HINT: All this can be written in the same line, using the ternary operator - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator)

@Reasonab1e
