### ISSUE TITLE
Not informative name "myTextarea"

### ISSUE THREAD

**Issue by abobykin** [abobykin/bingo#5]
in the line of code 

```const myTextarea = document.getElementById('task')``` please change the name of variable to describe clear meaning of the object its linked to.

Thnx!

**Comment by Reasonab1e** [comment]
I named this variable  "taskList" is it ok? @abobykin

**Comment by abobykin** [comment]
Hmm maybe for full description '''taskListTextarea''' is better ?

**Comment by abobykin** [comment]
@Reasonab1e

**Comment by abobykin** [comment]
I see this is done, closing
